server:
  port: 8013

spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.2.175:61616
    in-memory: false
    pool:
      enabled: true
      max-connections: 10
    packages:
      trust-all: true   #是否信任所有包，信任后所有包内的对象均可序列化传输
  jms:
    pub-sub-domain: true
debug: true

rocketmq:
  name-server: 192.168.2.175:9876 # 自己的RocketMQ-nameserver服务地址
  producer:
    send-message-timeout: 300000
    group: launch-group #一个生产者组